/**
 * Web service that accepts an optional list of product orders and returns
 * an updated products table.  If orders were received then they are written
 * to order header/detail tables.
 */
function sync(req, res) {
    // Write out orders if any exist
    if (req.body && req.body.orders) {
        // Write order header record and retrieve the order ID generated by the database
        var orderId = pjs.query("SELECT OHID FROM FINAL TABLE(INSERT INTO ORDHDR VALUES(DEFAULT, DEFAULT) WITH NC)", null, 1);

        // Write order detail records
        orderId = orderId.ohid;
        req.body.orders.forEach(function(order) {
            order.orid = orderId;
            pjs.query("INSERT INTO ORDDTL SET ? WITH NC", order);
        });

        // Code would go here to process the orders and update the product quantity numbers
    }

    // Send back a current copy of the product file
    var records = pjs.query("SELECT * FROM PRODUCTSP");

    if (records == null) {
        records = [];
    }

    var products = { products: records };

    res.send(products);
}

exports.run = sync;
